# File: .yamllint.yaml
extends: default

rules:
  line-length:
    max: 120
    level: warning
  truthy:
    level: warning
  comments:
    require-starting-space: true
    min-spaces-from-content: 1
  indentation:
    indent-sequences: consistent
  document-start:
    present: false

ignore: |
  .venv/**
  venv/**
  node_modules/**
